version: '3.9'
services:
  mongodb:
    image: mongo:5.0.6
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: sandboxVR
      MONGO_INITDB_DATABASE: catcher
    ports:
     - 27017:27017
  backend:
    build:
      context: ./backend
    environment:
      PORT: 8081
      DATABASE_HOST: mongodb
      DATABASE_PORT: 27017
      DATABASE: catcher
      DB_USERNAME: root
      DB_PASSWORD: sandboxVR
    ports:
      - 18082:8081
    depends_on:
      - mongodb
  # frontend:
  #   build:
  #     context: ./frontend
  #   ports:
  #     - 13000:3000
  #   links:
  #     - 'backend-consensys:be'
